### PR TITLE
actually reload the page on index error

### PR DESCRIPTION
**Pull request by dneise**
this should solve #13

### CODE REVIEW

**Comment by dneise** [comment]
Apart from #14, which does not really solve #13 but rather pushes the problem into the realm of the user of this library, there was a mistake in the retry logic of  `__getitem__`.

On IndexError the page was not requested again from the server, but the `connection_error_counter` was increased and one waited a little while. The actual reload however was missing.

**Comment by dneise** [comment]
We discussed this. Reloading the page was in indeed missing .. but this solution has other problems:

In case a page is delivered only partly, then `__getitem__(index=(1,1))` might succeed but `__getitem__(index=(2,1))` does not and leads to a reload .... 
after some time and some more reloads the table is fully build and returned to the user, who gets a result where the timestamp is much older than the other values .... pretty ugly.

All this is solved, when the retry logic is pushed into the users hands ans proposed in #14

**Comment by dneise** [comment]
So we could merge this ... it is not worse than before ... but ultimatively we want #14, I guess

**Comment by relleums** [comment]
I think you are right, and I missed to reload the payload in case of IndexError. Anyhow, we just realized that even this is working now, it might cause that different fields in the payload have been crawled at very different times (might be minutes apart). So the payload might not be related to the time stamp and might cause naughty errors.

**Pull request merged**
