### PR TITLE
Add missing stuff

### PR DESCRIPTION
**Pull request by MaxNoe**
* Remove wrong run_id from main page (This number has unfortunately nothing to do with our run id)

* Add observations page to get the real run_ids

* Add missing stuff on main page

### CODE REVIEW

**Comment by dneise** [comment]
Oh damn, it wasnt the run_id? 
Sorry I didn't even think about checking that.

**Comment by MaxNoe** [comment]
You can see how the number in the parenthese behaves here:
http://fact-project.org/overview_video/2017/03/24/test_video/20170324.mp4

Clearly not what we want.

**Comment by MaxNoe** [comment]
From smartfact.cc:

```
2863	                case MCP::State::kTakingData:
2864	                    out << fMcpConfigurationName;
2865	                    if (fFadControlDrsRuns[2]>0)
2866	                        out << "(" << fFadControlDrsRuns[2] << ")";
2867	                    break;
```

**Comment by dneise** [comment]
Ah so its the last drs4 calibration run, used at the moment.

Sure, that is clearly some information we need on the frontpage ....

**Comment by MaxNoe** [comment]
@dneise I fixed an issue with the date handling and added tests.

**Comment by dneise** [comment]
@MaxNoe yes, I am just looking at it. Thanks for all the work. It is pretty puzzling however ... "Add missing stuff" pretty much nails it ;-) ... this is a messy PR... but I think I can handle it mentally ... its still the beginning of the week. (Although we had a rough start already --> drive)

**Comment by dneise** [comment]
Why do you need the  `freeze_time` decorator for the tests? Am I missing something time dependent inside build_run?

**Comment by dneise** [comment]
Oh if the was just a standardized format we could use ... but alas human kind did not invent one ...

**Comment by dneise** [comment]
I'm sorry but this looks all very fine and nice to me. I cannot see any mistake.

**Pull request merged**
