### PR TITLE
added first tests

### PR DESCRIPTION
**Pull request by dneise**
* added some test resources
 * added some first tests
 * modified parser functions so changing smartfacturl has an effect
 * removed special `drive` function, renamed tracking and pointing instead

### CODE REVIEW

**Comment by MaxNoe** [comment]
I do not like only giving the base url! One should be able to give the full url. For example I downloaded test data and gave them names like `status_{datetime}`.data

**Comment by MaxNoe** [comment]
What do you think about
```{python}
def some_smartfact_foo(url=None):
   if url is None:
       url = baseurl + 'this_smartfact_foo.data' 
```

**Comment by dneise** [comment]
Done .. have a look

**Comment by dneise** [comment]
any news here? how do you feel about removing the `drive` function?
This is an API change.

**Comment by mackaiver** [comment]
I like it so far. Having seperate drive thingies kind of makes sense. Its the same with the Aux files right?

I also like the test. Maybe we can provide the test resource files as a fixture? I think pytest can do something like 
```
@pytest.fixture
def some_resource():
    ##load and return a resource needed by some tests
    return the_resource


def some_test(some_resource):
    #some testing in here.
```

What do you think? Anyways I think this can be merged

**Comment by dneise** [comment]
@mackaiver Thanks for pointing me towards fixtures ... I read a bit about it, but don't yet fully get how I should use it.
I made a proposal here ... I don't like it very much. looks like I'm using it wrong to me ... but works as well.

**Comment by dneise** [comment]
@mackaiver  I reverted back to the state without fixtures, but you can look at my funny tries here.
https://github.com/fact-project/smart_fact_crawler/pull/17/commits/661b19f5f64ff379533215d2d36cb59c430b38af
I would like to get some feedback on it ... if you have time

**Comment by mackaiver** [comment]
I also prefer the former version.  In my opinion this can be merged as this is really more a matter of cosmetics for the moment right? Maybe we add fixtures add some later point. Or not. I really have no strong opinion on this 👍

**Pull request merged**
