### PR TITLE
smartfact source names can have white spaces

### PR DESCRIPTION
**Pull request by relleums**
Since white spaces are also used by the Tablecrawler to split fields in a row, the fields must be joined again to get the full source name.

### CODE REVIEW

**Comment by MaxNoe** [comment]
I don't get it. We only split at tabs. Why should source names contain tabs?

**Comment by MaxNoe** [comment]
See: https://github.com/fact-project/smart_fact_crawler/blob/master/smart_fact_crawler/table_crawler.py#L27

**Comment by dneise** [comment]
Any news here?

**Comment by dneise** [comment]
We discussed this and Sebastian told me he actually saw problems during the night and his proposal in fact solved them ... so I vote for merging. Especially since I do not see any way, this proposal could be harmful ... at best it does nothing.

**Comment by dneise** [comment]
I've just added some test. [One of them ](https://github.com/fact-project/smart_fact_crawler/pull/17/commits/352a3d2dfac68ad56587fd212416f6b2280110b4) tries to check if there is a problem with source names containing spaces.

By pure luck, the test files I added are from a time where FACT pointed at Mrk 501 ... so they are suitable to test this, I think... please have a look at #17

**Comment by relleums** [comment]
Ok, I was hunting a ghost here, maybe I confused the version while I ran into the white space issue.

**Pull request closed without merging**
